### PR TITLE
api: Add prefix to conditons about cluster and node. #407

### LINKED ISSUE #407: Improvement:  The two Conditions in CRD are confused
**Is your feature request related to a problem? Please describe.**
```
$ kubectl describe mysqlclusters.mysql.radondb.com sample
```

```
**Status:
  Conditions:**
    Last Transition Time:  2022-03-11T09:18:40Z
    Status:                True
    Type:                  Initializing
    Last Transition Time:  2022-03-11T09:18:41Z
    Message:               0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
    Reason:                Unschedulable
    Status:                True
    Type:                  Error
    Last Transition Time:  2022-03-11T09:19:01Z
    Status:                True
    Type:                  Initializing
    Last Transition Time:  2022-03-11T09:27:51Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-03-14T06:32:35Z
    Message:               failed to ping host[http://sample-mysql-0.sample-mysql.default:6601/v1/xenon/ping], err: Get "http://sample-mysql-0.sample-mysql.default:6601/v1/xenon/ping": dial tcp: lookup sample-mysql-0.sample-mysql.default: no such host
    Status:                True
    Type:                  Error
    Last Transition Time:  2022-03-14T07:18:55Z
    Status:                True
    Type:                  Ready
  **Nodes:
    Conditions:**
      Last Transition Time:  2022-03-11T09:23:40Z
      Status:                False
      Type:                  Lagged
      Last Transition Time:  2022-03-14T07:18:43Z
      Status:                False
....
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by andyli029**
### Which issue(s) this PR fixes?

Fixes #407 

### What this PR does?

Summary:

### CODE REVIEW

**Comment by acekingke** [comment]
completed the reason why you change the codes.

**Comment by acekingke** [comment]
Use    `kubectl get mysql  -o jsonpath='{.items[0].status.conditions[*]}' ;`
or `kubectl get mysql  -o jsonpath='{.items[0].status.nodes[*]}' ; `

**Review by acekingke — CHANGES_REQUESTED** [review]
Why Change names？

**Comment by andyli029** [comment]
> Why Change names？

Follow k8s.

**Pull request closed without merging**
