### PR TITLE
cmd: Change HttpServer stop channel to buffered channel. #411

### PR DESCRIPTION
**Pull request by mgw2168**
### What type of PR is this?

/bug

### What this PR does?

Summary: If you use unbuffered channel, it is possible to lose the signal.

### Which issue(s) this PR fixes?

Fixes: https://github.com/radondb/radondb-mysql-kubernetes/issues/412

### CODE REVIEW

**Review by andyli029 — APPROVED** [review]
Add  #412  to the end of the commit log.

**Comment by mgw2168** [comment]
issue: https://github.com/radondb/radondb-mysql-kubernetes/issues/412

**Comment by acekingke** [comment]
LGTM

**Review by andyli029 — COMMENTED** [review]
LGTM.

**Pull request merged**
