### PR TITLE
config: Add podAntiAffinity to default sample yaml. #371

### PR DESCRIPTION
**Pull request by runkecheng**
### What type of PR is this?

/documentation
/enhancement

### Which issue(s) this PR fixes?

ref: #371 

### What this PR does?

Summary:

Add podAntiAffinity to default sample yaml. 

Guarantee to schedule nodes to different physical machines

### CODE REVIEW

**Comment by andyli029** [comment]
Improve the issue #371

**Review by acekingke — COMMENTED** [review]
LGTM

**Comment by runkecheng** [comment]
Using a new sample file may be better, if the default configuration of anti-affinity can be unable to deploy in the verification environment.

**Comment by runkecheng** [comment]
Using a new sample file may be better, if the default configuration of anti-affinity can be unable to deploy in the verification environment.

**Comment by andyli029** [comment]
> Using a new sample file may be better
ACK.

**Review by andyli029 — COMMENTED** [review]
LGTM.

**Pull request merged**
