### PR TITLE
*: support the cronjob to backup #215

### LINKED ISSUE #215: [Feature] support the cronjob to backup
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
use the cronjob schedule the backup job.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by acekingke**
### What type of PR is this?

/enhancement
### Which issue(s) this PR fixes?

Fixes  #215

### What this PR does?

Summary:

### CODE REVIEW

**Review by andyli029 — DISMISSED** [review]
Add sample yaml.

**Comment by andyli029** [comment]
Resolve conflicts.

**Comment by Nrehearsal** [comment]
[line here](https://github.com/acekingke/radondb-mysql-kubernetes/blob/8e1823b04e3755b442c1e05f9c6c665ad981121d/controllers/backupcron_controller.go#L133)

@acekingke 

```backup.CronJob.Image``` should be set in ```func (j *CronJob) Run()``` by fetching mysqlcluster,  putting cluster-related variables into memory will cause data to be out of sync

**Comment by acekingke** [comment]
> [line here](https://github.com/acekingke/radondb-mysql-kubernetes/blob/8e1823b04e3755b442c1e05f9c6c665ad981121d/controllers/backupcron_controller.go#L133)
> 
> @acekingke
> 
> `backup.CronJob.Image` should be set in `func (j *CronJob) Run()` by fetching mysqlcluster, putting cluster-related variables into memory will cause data to be out of sync

is fixed.

**Comment by Nrehearsal** [comment]
> > [line here](https://github.com/acekingke/radondb-mysql-kubernetes/blob/8e1823b04e3755b442c1e05f9c6c665ad981121d/controllers/backupcron_controller.go#L133)
> > @acekingke
> > `backup.CronJob.Image` should be set in `func (j *CronJob) Run()` by fetching mysqlcluster, putting cluster-related variables into memory will cause data to be out of sync
> 
> is fixed.

get!

**Review by zhl003 — APPROVED** [review]
LGTM

**Review by runkecheng — APPROVED** [review]

**Review by andyli029 — APPROVED** [review]
LGTM.

**Pull request merged**
