### PR TITLE
syncer: failed to patch pod labels.

### PR DESCRIPTION
**Pull request by runkecheng**
### What type of PR is this?

/bug

### Which issue(s) this PR fixes?
Fixes #

### What this PR does?

Summary:

Mergefrom() needs to use the old object.

### CODE REVIEW

**Review by zhl003 — APPROVED** [review]
look good

**Review by acekingke — APPROVED** [review]
LGTM

**Review by andyli029 — COMMENTED** [review]
commit log: 
add `fix`

**Comment by runkecheng** [comment]
> commit log: add `fix`

There is no corresponding issue

**Pull request merged**
