### PR TITLE
test: example code for e2e.

### PR DESCRIPTION
**Pull request by runkecheng**
### What type of PR is this?

/enhancement

### Which issue(s) this PR fixes?

Fixes #

### What this PR does?

Summary:

- [x] example code for e2e
- [ ] ci

### step1: Configure environment variables

```
export KUBECONFIG=$HOME/.kube/config
```
### step2: Configure test context

Fill `Endpoints` in `text_context.go` like 

```
flag.StringVar(&TestContext.KubeHost, "kubernetes-host", "https://139.198.30.60:16443", "The kubernetes host, or apiserver, to connect to")
```

> If the host and the K8s cluster are not in the same network, you need to configure external network access.

### Run test

example

```
/radondb-mysql-kubernetes/test/e2e$ go test -timeout 3000s -run ^TestE2E$
go test -v ./test/e2e   -timeout 20m
=== RUN   TestE2E
STEP: Creating framework with timeout: 1200
Running Suite: MySQL Operator E2E Suite
=======================================
Random Seed: 1639707312 - Will randomize all specs
Will run 1 of 1 specs

STEP: Install operator
NAME: demo
LAST DEPLOYED: Fri Dec 17 10:15:14 2021
NAMESPACE: mysql-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You can create a new mysqlcluster by issuing:

cat <<EOF | kubectl apply -f-
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlCluster
metadata:
  name: sample
spec:
  replicas: 3
EOF
MySQL Cluster E2E Tests 
  scale out/in a cluster, 2 -> 3 -> 5 -> 3 -> 2
  /home/runkecheng/goCode/src/radondb-mysql-kubernetes/test/e2e/cluster/cluster.go:77
[BeforeEach] MySQL Cluster E2E Tests
  /home/runkecheng/goCode/src/radondb-mysql-kubernetes/test/e2e/framework/framework.go:63
STEP: creating a kubernetes client
STEP: create a namespace api object (e2e-mc-1-bvrb2)
[BeforeEach] MySQL Cluster E2E Tests
  /home/runkecheng/goCode/src/radondb-mysql-kubernetes/test/e2e/cluster/cluster.go:58
STEP: creating a new cluster
STEP: testing the cluster readiness
STEP: create sysbench pod for preparing data
STEP: wait pod ready
STEP: testing the data readiness
[It] scale out/in a cluster, 2 -> 3 -> 5 -> 3 -> 2
  /home/runkecheng/goCode/src/radondb-mysql-kubernetes/test/e2e/cluster/cluster.go:77
STEP: create sysbench pod for testing oltp
STEP: wait pod ready
STEP: test cluster is ready after scale out 2 -> 3
STEP: test cluster is ready after scale out 3 -> 5
STEP: test cluster is ready after scale in 5 -> 3
STEP: test cluster is ready after scale in 3 -> 2
[AfterEach] MySQL Cluster E2E Tests
  /home/runkecheng/goCode/src/radondb-mysql-kubernetes/test/e2e/framework/framework.go:64
STEP: Collecting logs
STEP: Run cleanup actions
STEP: Delete testing namespace

• [SLOW TEST:1023.235 seconds]
MySQL Cluster E2E Tests
/home/runkecheng/goCode/src/radondb-mysql-kubernetes/test/e2e/cluster/cluster.go:39
  scale out/in a cluster, 2 -> 3 -> 5 -> 3 -> 2
  /home/runkecheng/goCode/src/radondb-mysql-kubernetes/test/e2e/cluster/cluster.go:77
------------------------------
STEP: Remove operator release
release "demo" uninstalled
STEP: Delete operator namespace


Ran 1 of 1 Specs in 742.686 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
```

### CODE REVIEW

**Comment by acekingke** [comment]
Got error：
Random Seed: 1639542724 - Will randomize all specs
Will run 1 of 1 specs

Failure [0.003 seconds]
[BeforeSuite] BeforeSuite 
/root/radondb-mysql-kubernetes/test/e2e/e2e.go:50

  can't instantiate k8s client: the server rejected our request for an unknown reason

  /root/radondb-mysql-kubernetes/test/e2e/e2e.go:57

**Comment by acekingke** [comment]
need set  env
```
 "KUBERNETES_SERVICE_HOST":"xxxx",
  "KUBERNETES_SERVICE_PORT":"6443",
"ACK_GINKGO_DEPRECATIONS":"1.16.5"
```

**Comment by acekingke** [comment]
image

**Comment by acekingke** [comment]
use `https:// ` it works.

**Comment by runkecheng** [comment]
image

**Pull request closed without merging**
