### PR TITLE
sidecar: Skip `reset slave all` when initialization.

### LINKED ISSUE #448: [bug]restore new cluster from s3 object storage in mysql 8.0，mysql container can't start
**Describe the problem**
restore new cluster from s3 object storage in mysql 8.0，mysql container can't start
e92aa036cf0ed53f8d5c443f14028c7

**To Reproduce**

1.Backup from cluster，then produce s3 back file
2.restore new cluster from s3 object storage

**Expected behavior**
new cluster start successful

**Environment:**
mysql version 8.0

- RadonDB MySQL version:

### LINKED ISSUE #450: [bug] Slave is not configured or failed to initialize properly.
**Describe the problem**

Initialization error, But the cluster can be started normally, elections.

**To Reproduce**

```
init mysql log:
 2022-04-14T15:41:38.072702+08:00 1 [ERROR] 1794  Slave is not configured or failed to initialize properly. You must at least set --server-id to enable either a master or a slave. Additional error messages can be found in the MySQL error log.

 2022-04-14T15:41:38.073601+08:00 0 [ERROR] Aborting
```

**Expected behavior**

**Environment:**

- RadonDB MySQL version: v2.2.0

### PR DESCRIPTION
**Pull request by acekingke**
### What type of PR is this?

/bug

### Which issue(s) this PR fixes?

Fixes #450

### What this PR does?

Summary: Skip reset slave all when initialization.

### CODE REVIEW

**Comment by runkecheng** [comment]
This PR and Issue are inconsistent.

**Comment by andyli029** [comment]
Fix commit log.

**Review by andyli029 — CHANGES_REQUESTED** [review]
Fix commit log.

**Review by runkecheng — APPROVED** [review]

**Review by andyli029 — APPROVED** [review]

**Comment by andyli029** [comment]
LGTM.

**Pull request merged**
